# Generated by Django 4.2 on 2024-01-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/images/user-default.png', null=True, upload_to='profiles/images/'),
        ),
    ]
