version: '3.7'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    command: memcached -m 128
    ports:
      - "11211:11211"

  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "courses_project.wsgi:application"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Collected static files
      - ./static/media:/app/static/media  # Media files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - memcached

  celery_worker:
    build: .
    command: ["celery", "-A", "courses_project", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - memcached
      - web

  celery_beat:
    build: .
    command: ["celery", "-A", "courses_project", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - celery_worker

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles  # Serve static files
      - ./static/media:/app/static/media  # Serve media files
    depends_on:
      - web
