# Generated by Django 4.2 on 2023-09-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.learner'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_learners',
            field=models.ManyToManyField(related_name='courses_enrolled', through='learning.CourseEnrollment', to='users.learner'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='courses.tag'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='baselessonstep',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (1, 5))), name='rating_between_1_5'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('course', 'learner'), name='unique_review_per_learner_per_course'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizlessonstep'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
        migrations.AddField(
            model_name='codechallengetestcase',
            name='code_challenge_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='courses.codechallengelessonstep'),
        ),
        migrations.AddField(
            model_name='codechallengelessonstep',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.programminglanguage'),
        ),
    ]
