# Generated by Django 4.2 on 2023-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
