# Generated by Django 4.2 on 2023-04-27 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='quizlessonstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='textlessonstep',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='videolessonstep',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizlessonstep',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textlessonstep',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolessonstep',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='quizlessonstep',
            unique_together={('lesson', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='textlessonstep',
            unique_together={('lesson', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='videolessonstep',
            unique_together={('lesson', 'order')},
        ),
    ]
