# Generated by Django 4.2 on 2023-09-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_codechallengelessonstep_programminglanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallengetestcase',
            name='code_challenge_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='courses.codechallengelessonstep'),
        ),
    ]
