# Generated by Django 4.2 on 2024-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=50, null=True),
        ),
    ]
