# Generated by Django 4.2 on 2024-01-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallengetestcase',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='courses/images/default.jpg', null=True, upload_to='courses/images/'),
        ),
        migrations.AlterField(
            model_name='videolessonstep',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterUniqueTogether(
            name='codechallengetestcase',
            unique_together={('code_challenge_step', 'input')},
        ),
    ]
