# Generated by Django 4.2 on 2024-05-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_codechallengetestcase_input_alter_course_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingProblemLessonStep',
            fields=[
                ('base_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sorting_problem_step', serialize=False, to='courses.baselessonstep')),
                ('title', models.CharField(max_length=100)),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SortingProblemOption',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=100)),
                ('correct_order', models.PositiveIntegerField()),
                ('sorting_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.sortingproblemlessonstep')),
            ],
        ),
    ]
