# Generated by Django 4.2 on 2024-05-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_sortingproblemlessonstep_sortingproblemoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProblemLessonStep',
            fields=[
                ('base_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='text_problem_step', serialize=False, to='courses.baselessonstep')),
                ('title', models.CharField(max_length=100)),
                ('statement', models.TextField()),
                ('correct_answer', models.TextField()),
                ('case_sensitive', models.BooleanField(default=False)),
                ('allow_regex', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sortingproblemoption',
            options={'ordering': ['correct_order']},
        ),
    ]
