# Generated by Django 4.2 on 2024-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='learnerquizperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='learnerquizperformance',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='learnerquizperformance',
            name='quiz_step',
        ),
        migrations.DeleteModel(
            name='AssessmentAnalytics',
        ),
        migrations.DeleteModel(
            name='LearnerQuizPerformance',
        ),
    ]
