# Generated by Django 4.2 on 2023-09-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('users', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprogress',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.learner'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.learner'),
        ),
        migrations.AlterUniqueTogether(
            name='learnerprogress',
            unique_together={('learner', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('course', 'learner')},
        ),
    ]
