# Generated by Django 4.2 on 2023-09-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechallengesubmission',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
