# Generated by Django 4.2 on 2024-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechallengesubmission',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
