# Generated by Django 4.2 on 2024-05-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_codechallengetestcase_input_alter_course_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_codechallengesubmission_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerQuizPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('passed', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizlessonstep')),
            ],
            options={
                'unique_together': {('learner', 'quiz_step')},
            },
        ),
    ]
