# Generated by Django 4.2 on 2024-05-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_textproblemlessonstep_and_more'),
        ('learning', '0004_learnerquizperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerAssessmentStepPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('passed', models.BooleanField(default=False)),
                ('base_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.baselessonstep')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('learner', 'base_step')},
            },
        ),
        migrations.DeleteModel(
            name='LearnerQuizPerformance',
        ),
    ]
