# Generated by Django 4.2 on 2024-06-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learnerassessmentstepperformance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechallengesubmission',
            name='attempts',
        ),
    ]
